use customer_behavior;
show tables;
select * from customer;

				# total revenue generated by M vs F
select gender, sum(purchase_amount) 
from customer 
group by gender;

				# customer purchased more than avg. even after using discounts
select customer_id, purchase_amount 
from customer 
where discount_applied = 'yes' and purchase_amount >= (select AVG(purchase_amount) from customer);

				# top 5 products with highest average review rating
select item_purchased, round(avg(review_rating),2) as Avg_Rating from customer 
group by item_purchased 
order by avg(review_rating) desc limit 5;

				# compare the avg purchase amnt b/w standard & express shipping
select shipping_type, round(avg(purchase_amount), 2) as Avg_Amount from customer
where shipping_type in ('express','standard')
group by shipping_type;

				# compare average spend and total revenue b/w subscribers and non-subscr.
select count(customer_id) as Total_Customers, 
subscription_status, 
round(avg(purchase_amount),2) as Avg_Amnt, 
round(sum(purchase_amount),2)as Total_Amnt 
from customer
group by subscription_status;         

					# 5 products having highest %age of purchases with discount applied
select item_purchased, 
round(sum(case when discount_applied = 'yes'then 1 else 0 end) * 100 / count(*), 2) as Discount_Percentage
from customer
group by item_purchased
order by Discount_Percentage desc limit 5;

					# segement the customers type based on prev purchases and count each segment
with customer_type as (
	select previous_purchases,
    case
		when previous_purchases <= 2 then 'New Customers'
        when previous_purchases between 3 and 10 then 'Returning Customers'
        else 'Loyal Customers' end as 'customer_segmentation'
from customer)

select customer_segmentation, count(*) as 'No. of Customers' from customer_type group by customer_segmentation;

					# top 3 most purchased products within each category
with item_counts as (
	select category, item_purchased, count(customer_id) as total_orders,
    ROW_NUMBER() over(partition by category order by count(customer_id) desc) as item_rank
    from customer
    group by category, item_purchased)
    
select item_rank, category, item_purchased, total_orders from item_counts where item_rank <= 3;

					# customers who r repeat buyers and likely to subscribe
select subscription_status, count(customer_id) as repeat_buyers
from customer 
where previous_purchases > 5
group by subscription_status;

					# revenue contribution ofeach age group
select age_group, sum(purchase_amount) as Total_Revenue from customer 
group by age_group 
order by Total_Revenue desc;		